# Site settings
title: Novo Blog RNP
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Novas postagens
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: POPRNP
github_username:  POPRNP

# Build settings
markdown: kramdown
